# Generated by Django 6.0 on 2025-12-29 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('technician', 'Technician'), ('admin', 'Admin'), ('messenger admin', 'messenger admin')], default='customer', max_length=20),
        ),
    ]
