# Generated by Django 6.0 on 2026-01-04 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_logintoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoginToken',
        ),
    ]
